apache/dolphinscheduler-website

README.md
blog/en-us/meetup_2019_10_26.md
blog/zh-cn/meetup_2019_10_26.md
md_json/blog.json
package-lock.json
site_config/blog.js
site_config/community.jsx

Add meetup blog

---

blog/en-us/meetup_2019_10_26.md

Just try to go through the whole process

update the close time on blog

---

src/components/footer/index.scss
src/components/header/index.scss

icon css modify

---

.github/workflows/website.yml

modify auto deploy use github token with error

modify auto deploy

---

.github/workflows/website.yml

clear files on the branch of asf

clear files on the branch of asf 

---

index.html
package-lock.json
package.json

revert webpack version to 3.0.0

webpack version

---

.asf.yaml

asf.yml modify

---

docs/en-us/development/contribute.md
docs/zh-cn/development/contribute.md

add unit test guide

---

docs/en-us/user_doc/frontend-deployment.md
docs/zh-cn/user_doc/frontend-deployment.md

Modify front-end deployment manual deployment instructions

Modify front-end deployment manual deployment instructions

---

.github/workflows/website.yml
baidu_verify_D9hyOepqUF.html
googleff48c3fa45891a20.html
sitemap.xml

seo optimization

---

.github/workflows/website.yml

github action build files

---

blog/en-us/meetup_2019_12_08.md
blog/zh-cn/meetup_2019_12_08.md
docs/en-us/development/architecture-design.md
docs/en-us/development/frontend-development.md
docs/en-us/faq.md
docs/zh-cn/development/architecture-design.md
docs/zh-cn/faq.md
site_config/community.jsx

english manual contains chinese

 english manual contains chinese 

---

docs/en-us/user_doc/frontend-deployment.md
docs/zh-cn/user_doc/frontend-deployment.md

change and complement jetty deployment instructions

change and complement jetty deployment instructions

---

docs/en-us/release/upgrade.md
docs/zh-cn/release/upgrade.md
docs/zh-cn/user_doc/download.md
site_config/site.js

1.update upgreade file
2.add download in chinese

update upgreade md and add download in chinese

---

docs/en-us/user_doc/backend-deployment.md
docs/en-us/user_doc/frontend-deployment.md
docs/zh-cn/user_doc/backend-deployment.md
docs/zh-cn/user_doc/frontend-deployment.md
site_config/site.js

update download url in docs of deployment

update download url in docs of deployment

---

site_config/docs.js

update API url

---

docs/en-us/1.2.0/user_doc/backend-deployment.md
docs/zh-cn/1.2.0/user_doc/backend-deployment.md

update download url

---

docs/en-us/development/release.md

add the doc about how to release the version

add the doc about how to release

---

docs/en-us/development/release.md
docs/en-us/user_doc/deployment.md
docs/en-us/user_doc/upgrade.md

add upgrade doc and deployment doc in the default

add upgrade doc and deployment doc in the default

---

src/pages/home/index.jsx

get starcount data may be make the website load speed slow

get starcount data may be make the website load speed slow

---

src/pages/home/index.jsx

update star and fork data

---

docs/zh-cn/1.2.0/user_doc/cluster-deployment.md
docs/zh-cn/1.2.0/user_doc/standalone-deployment.md
docs/zh-cn/1.2.1/user_doc/cluster-deployment.md
docs/zh-cn/1.2.1/user_doc/standalone-deployment.md
package.json

correct some error

---

docs/en-us/1.2.0/user_doc/cluster-deployment.md
docs/en-us/1.2.0/user_doc/standalone-deployment.md

display login picture in en-us deployment md

display login picture in en-us deployment md

---

site_config/home.jsx

Fixes 1411#, correct word speel from Scanerios to Scenarios.

correct word speel from Scanerios to Scenarios

---

docs/zh-cn/1.2.0/user_doc/backend-development.md

update backend-development.md  

---

docs/en-us/1.2.0/user_doc/backend-deployment.md
docs/en-us/1.2.0/user_doc/backend-development.md
docs/en-us/1.2.0/user_doc/cluster-deployment.md
docs/en-us/1.2.0/user_doc/standalone-deployment.md
docs/en-us/1.2.0/user_doc/system-manual.md
docs/en-us/1.2.1/user_doc/backend-deployment.md
docs/en-us/1.2.1/user_doc/system-manual.md
docs/en-us/release/faq.md
docs/en-us/user_doc/deployment.md
docs/zh-cn/1.2.0/user_doc/backend-deployment.md
docs/zh-cn/1.2.0/user_doc/backend-development.md
docs/zh-cn/1.2.0/user_doc/cluster-deployment.md
docs/zh-cn/1.2.0/user_doc/deployparam.md
docs/zh-cn/1.2.0/user_doc/masterserver-code-analysis.md
docs/zh-cn/1.2.0/user_doc/standalone-deployment.md
docs/zh-cn/1.2.0/user_doc/system-manual.md
docs/zh-cn/1.2.1/user_doc/backend-deployment.md
docs/zh-cn/1.2.1/user_doc/cluster-deployment.md
docs/zh-cn/1.2.1/user_doc/deployparam.md
docs/zh-cn/1.2.1/user_doc/standalone-deployment.md
docs/zh-cn/1.2.1/user_doc/system-manual.md
docs/zh-cn/release/faq.md

fix professional vocabulary including MySQL, PostgreSQL and Zookeeper.
[issue link](https://github.com/apache/incubator-dolphinscheduler/issues/2478)

[BUG FIX] fix 2478 The professional vocabulary is misspelled

---

docs/zh-cn/1.2.0/user_doc/development-environment-setup.md

*Add the MySQL dev detail description.*
- *Add the MySQL dev detail description in docs/zh-cn/1.2.0/user_doc/development-environment-setup.md.*

[Feature][docs-zh] Add the MySQL dev detail description

---

docs/zh-cn/1.3.0/user_doc/cluster-deployment.md
docs/zh-cn/1.3.0/user_doc/standalone-deployment.md
docs/zh-cn/1.3.0/user_doc/upgrade.md

update standalone deployment doc

update standalone deployment doc

---

docs/en-us/1.3.0/user_doc/cluster-deployment.md
docs/en-us/1.3.0/user_doc/hardware-environment.md
docs/en-us/1.3.0/user_doc/standalone-deployment.md
docs/zh-cn/1.3.0/user_doc/metadata-1.3.md
docs/zh-cn/1.3.0/user_doc/standalone-deployment.md
docs/zh-cn/1.3.0/user_doc/system-manual.md
docs/zh-cn/1.3.0/user_doc/upgrade.md
site_config/site.js

add cluster and standalone deployment in english and update some contents in chinese

add cluster and standalone deployment in english and update some contents in chinese

---

site_config/site.js

remove docs link

---

docs/zh-cn/development/DS-License.md
md_json/docs.json
site_config/development.js

add DS-License.md

---

docs/zh-cn/development/development-environment-setup.md

Update developer documentation for 1.3.0

update development doc

---

docs/zh-cn/1.3.0/user_doc/configuration-file.md

update   default     worker.listen.port: 1234

update   default     worker.listen.port: 1234

---

site_config/docs1-3-1.js
src/pages/documentation/index.jsx

add docs1-3-1.js in order to display the left frame correctly

add docs1-3-1.js in order to display the left frame correctly

---

docs/en-us/1.3.1/user_doc/quick-start.md
docs/zh-cn/1.3.1/user_doc/upgrade.md
site_config/site.js

update upgrade doc of 1.3.1

---

docs/zh-cn/1.2.1/user_doc/microbench.md
docs/zh-cn/development/microbench.md
md_json/docs.json
site_config/docs1-2-1.js

add Benchmark doc

---

docs/en-us/1.3.1/user_doc/cluster-deployment.md
docs/en-us/1.3.1/user_doc/standalone-deployment.md
docs/zh-cn/1.3.1/user_doc/cluster-deployment.md
docs/zh-cn/1.3.1/user_doc/standalone-deployment.md

1.update mysql connection example
2.change dolphinscheduler-backend to dolphinscheduler-bin

update mysql connection example

---

docs/en-us/1.3.1/user_doc/cluster-deployment.md
docs/en-us/1.3.1/user_doc/standalone-deployment.md
docs/zh-cn/1.3.1/user_doc/cluster-deployment.md
docs/zh-cn/1.3.1/user_doc/standalone-deployment.md

fix spelling mistake:should be password not passowrd

fix spelling mistake:should be password not passowrd

---

docs/en-us/1.3.1/user_doc/upgrade.md
docs/zh-cn/1.2.0/user_doc/upgrade.md
docs/zh-cn/1.2.1/user_doc/upgrade.md
docs/zh-cn/1.3.1/user_doc/upgrade.md
docs/zh-cn/1.3.2/user_doc/upgrade.md

change upgrade file name from upgrade-escheduler.sh to upgrade-dolphinscheduler.sh

change upgrade file name from upgrade-escheduler.sh to upgrade-dolphinscheduler.sh

---

docs/en-us/1.3.2/user_doc/upgrade.md

I translate https://dolphinscheduler.apache.org/zh-cn/docs/1.3.2/user_doc/upgrade.html this document into English.

Translate en 1.3.2 upgrade document.

---

docs/en-us/1.3.2/user_doc/cluster-deployment.md
site_config/docs1-3-2.js

Improve English documentation about standalone-deployment and cluster-deployment.

[Improvement-3871][document] Add standalone-deployment and cluster-deployment english document

---

docs/en-us/1.3.2/user_doc/standalone-deployment.md
site_config/docs1-3-2.js

translate 1.3.2 standalone-deployment.md en version

translate 1.3.2 standalone-deployment.md en version

---

docs/zh-cn/1.3.1/user_doc/system-manual.md
docs/zh-cn/1.3.2/user_doc/system-manual.md

update 3.1 HDFS resource configuration

update 3.1 HDFS resource configuration

---

docs/en-us/1.3.1/user_doc/system-manual.md

update english doc : 3.1 HDFS resource configuration

update english doc : 3.1 HDFS resource configuration

---

docs/zh-cn/development/contribute.md

fix one contribute.md wrong Chinese word

---

docs/en-us/development/contribute.md
docs/en-us/development/document.md

WebsiteDocs-1: Translated the Contribution page to English

WebsiteDocs-1: Translated the Contribution page to English

---

docs/en-us/development/contribute.md
docs/zh-cn/development/contribute.md
md_json/docs.json
site_config/development.js

some url can't open , update commit_message to commit-message

[fix error] commit-message url can't open 

---

docs/en-us/development/contribute.md
docs/zh-cn/development/contribute.md
md_json/docs.json
site_config/development.js

Reverts apache/incubator-dolphinscheduler-website#205

Revert "[fix error] commit-message url can't open "

---

site_config/docs1-2-1.js
site_config/docs1-3-1.js
site_config/docs1-3-2.js
site_config/docs1-3-3.js

fix small spell error about open api link "lang=en"

fix small spell error about open api link "lang=en"

---

docs/zh-cn/1.3.3/user_doc/system-manual.md

Fix Flink doc

---

docs/zh-cn/1.3.3/user_doc/quick-start.md
docs/zh-cn/1.3.3/user_doc/system-manual.md

What is the purpose of the pull request
[4077](https://github.com/apache/incubator-dolphinscheduler/issues/4077)

[Fix-4077][website] replace good quality pictures for system manual

---

site_config/docs1-3-3.js

add the 扩/缩容 LINK TO OFFICIAL WEBSITE

[FIX-#4202][doc] ADD A LINK TO OFFICIAL WEBSITE

---

docs/zh-cn/development/release.md

[Improvement] update release process doc

---

docs/en-us/community/security.md
docs/en-us/community/team.md

Add team and security introduction under community

Add team and security introduction under community

---

docs/zh-cn/1.3.1/user_doc/quick-start.md
docs/zh-cn/1.3.2/user_doc/quick-start.md

Update worker group information

---

docs/en-us/community/release.md
docs/en-us/community/security.md

move release introduction to community

move release introduction to community

---

docs/en-us/development/contribute.md
docs/en-us/development/development-environment-setup.md
docs/en-us/development/document.md
docs/zh-cn/development/contribute.md
docs/zh-cn/development/development-environment-setup.md
docs/zh-cn/development/document.md
md_json/docs.json
site_config/development.js

1.fix zookeeper download url , version 3.6.1 is not exist ,use 3.6.2 instead;
2.There's a space bar missing between 'docsite' and '-g';
3.fix 'commit_message' to 'commit-message' in some file.

Fix zk download url and link path

---

site_config/community.js

update community.js add link of team,security and release

update community.js add link of team,security and release

---

docs/zh-cn/development/release.md

Update release new version process

Update release new version process

---

site_config/docs1-3-2.js
site_config/docs1-3-3.js
site_config/docs1-3-4.js

update error metadata version

---

.github/workflows/website.yml

github action plugin

---

community/zh-cn/team.md

Switch  Chinese brackets to English brackets

fix error link

---

site_config/docs.js
site_config/site.js

remove online demo table in the navigation bar

---

site_config/docs.js
site_config/site.js

Remove online demo

---

src/pages/home/index.jsx
src/pages/home/index.scss
utils/index.js

Support to update star and fork dynamically

---

docs/zh-cn/1.3.4/user_doc/configuration-file.md

fix cn configuration-file.md some wrong words

fix cn configuration-file.md some wrong words

---

docs/zh-cn/1.3.4/user_doc/task-structure.md

fix cn task-structure.md some wrong words

fix cn task-structure.md some wrong words

---

docs/en-us/1.3.4/user_doc/configuration-file.md

translate configuration-file into en-us

translate configuration-file into en-us

---

docs/en-us/1.3.4/user_doc/task-structure.md

translate task-structure into en-us

translate task-structure into en-us

---

site_config/docs1-3-4.js

configure configuration-file.md&task-structure.md to docs1-3-4.js

add configuration-file.md&task-structure.md to docs1-3-4.js

---

development/en-us/frontend-development.md
development/zh-cn/frontend-development.md

…face parameter transfer method

Front-end development documents supplement Content-Type request interface parameter transfer method

---

community/zh-cn/release.md

update how to release in chinese

update how to release in chinese

---

README.md
community/en-us/development/document.md
community/zh-cn/development/document.md

According to github readme.md, change website node version from 8 to 10.

change node version from 8 to 10.

---

docs/en-us/1.3.5/user_doc/docker-deployment.md
docs/en-us/1.3.5/user_doc/kubernetes-deployment.md
docs/zh-cn/1.3.5/user_doc/docker-deployment.md
docs/zh-cn/1.3.5/user_doc/kubernetes-deployment.md
site_config/docs1-3-5.js

- Update docker deployment
- Add k8s deployment

Update docker deployment and add k8s deployment

---

.htaccess
gulpfile.js
site_config/site.js
template.ejs

1. Fix html cache by `.htaccess`
2. Check copyToDist exist

Fix html cache and check copyToDist exist

---

README.md
docs/en-us/1.2.1/user_doc/architecture-design.md
docs/en-us/1.3.1/user_doc/architecture-design.md
docs/zh-cn/1.2.1/user_doc/architecture-design.md
docs/zh-cn/1.3.1/user_doc/architecture-design.md
docs/zh-cn/1.3.2/user_doc/architecture-design.md
docs/zh-cn/1.3.3/user_doc/architecture-design.md
docs/zh-cn/1.3.4/user_doc/architecture-design.md
docs/zh-cn/1.3.5/user_doc/architecture-design.md

chore: fix Java code

---

community/en-us/team.md
community/zh-cn/team.md
development/en-us/development-environment-setup.md
development/zh-cn/development-environment-setup.md

Submit the pull request based on this [issue](https://github.com/apache/dolphinscheduler/issues/5295),

[WebSite]Information correction after graduation

---

docs/en-us/1.3.5/user_doc/load-balance.md
site_config/docs1-3-5.js

[load-balance](https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/load-balance.html)

docs: add en-us load-balance.md

---

src/components/header/index.jsx
src/components/header/index.scss
src/pages/home/index.jsx

Optimize the style of the head of the index page.when the page moves to the area with white background, the background color of the head turns to black.

Optimize the style of the head of the index page.

---

package.json
src/pages/docs/index.md.jsx

Fix page flash problem in documentation

---

docs/en-us/1.3.5/user_doc/docker-deployment.md
docs/en-us/1.3.5/user_doc/kubernetes-deployment.md
docs/en-us/1.3.6/user_doc/docker-deployment.md
docs/en-us/1.3.6/user_doc/kubernetes-deployment.md
docs/zh-cn/1.3.5/user_doc/docker-deployment.md
docs/zh-cn/1.3.5/user_doc/kubernetes-deployment.md
docs/zh-cn/1.3.6/user_doc/docker-deployment.md
docs/zh-cn/1.3.6/user_doc/kubernetes-deployment.md

3c9a6388 Add manage docs for docker
8297be3c Add manage docs for k8s

Add manage docs for docker and k8s

---

site_config/home.jsx
src/pages/home/index.jsx
src/pages/home/index.scss

1、Add events&news to the home page.

Add events&news to the home page.

---

docs/en-us/1.3.6/user_doc/system-manual.md

Error describing complement data flow  with English document;

Error describing complement data flow  with English document;

---

site_config/site.js
src/components/header/index.jsx
src/components/header/index.scss
src/pages/home/index.jsx

add meetup message on the header,both of the english and chinese

add meetup message on the header

---

site_config/site.js
src/components/header/index.jsx
src/components/header/index.scss
src/pages/home/index.jsx

Reverts apache/dolphinscheduler-website#362

remove meetup message on the header

---

blog/en-us/DAG.md
blog/zh-cn/DAG.md
site_config/blog.js

According to [DAG](https://dolphinscheduler.apache.org/en-us/blog/DAG.html), add the Chinese version.

Add the blog in Chinese about DAG.md 

---

docs/zh-cn/dev/user_doc/globalParams.md
site_config/docsdev.js

add the doc about the detail add the user operation of the global Params

add global Params doc

---

docs/en-us/dev/user_doc/alert_spi.md
docs/zh-cn/dev/user_doc/alert_spi.md

According to this [document](https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/alert_spi.html), then translated it.

[Summer2021] Translate the alert_spi.md

---

docs/en-us/dev/user_doc/dev-run.md
site_config/docsdev.js

Translate the [dev-run](https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/dev_run.html) page.

[SOC] Translate the dev-run page

---

site_config/blog.js
site_config/community.jsx
site_config/docs1-3-6.js
site_config/site.js
src/components/header/index.jsx
src/components/header/index.scss
src/pages/community/index.jsx
src/pages/community/index.scss
src/pages/docs/index.md.jsx

1、 modify the top title "document" and "asf" when the mouse leave the title I want to close the list.
2、Deleted duplicate content：News

modified: homePage mousemove && community module delete repeat message

---

docs/en-us/dev/user_doc/dev_quick_start.md
docs/zh-cn/dev/user_doc/dev_quick_start.md
site_config/docsdev.js
site_config/site.js

According to [Dev_Quick_Start](https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/dev_quick_start.html) and translate it.

[SOC] Translate dev_quick_start

---

blog/en-us/DAG.md
blog/zh-cn/DAG.md

updating Details for the dag picture

Updating Details for the dag picture

---

docs/en-us/2.0.0/user_doc/guide/installation/docker.md
docs/en-us/2.0.0/user_doc/guide/installation/kubernetes.md
docs/en-us/2.0.0/user_doc/guide/installation/pseudo-cluster.md
docs/en-us/dev/user_doc/guide/installation/docker.md
docs/en-us/dev/user_doc/guide/installation/kubernetes.md
docs/en-us/dev/user_doc/guide/installation/pseudo-cluster.md
docs/zh-cn/2.0.0/user_doc/guide/installation/docker.md
docs/zh-cn/2.0.0/user_doc/guide/installation/kubernetes.md
docs/zh-cn/2.0.0/user_doc/guide/installation/pseudo-cluster.md
docs/zh-cn/2.0.0/user_doc/upgrade.md
docs/zh-cn/dev/user_doc/guide/installation/docker.md
docs/zh-cn/dev/user_doc/guide/installation/kubernetes.md
docs/zh-cn/dev/user_doc/guide/installation/pseudo-cluster.md
docs/zh-cn/dev/user_doc/upgrade.md

upgrade to 8.0.16 cc: @caishunfeng

Upgrade msyql jdbc connector to 8.0.16

---

site_config/docs2-0-0.js

add 2.0.0 doc

---

docs/en-us/2.0.0/user_doc/architecture/design.md
docs/zh-cn/2.0.0/user_doc/architecture/design.md

update 2.0 architecture

---

site_config/docs2-0-0.js

add docs2.0.0

---

docs/zh-cn/2.0.0/user_doc/architecture/designplus.md
site_config/docs2-0-0.js

up docs2.0.0.js

---

docs/zh-cn/2.0.0/user_doc/architecture/designplus.md
site_config/docs2-0-0.js

up desigonplus / docs.2.0.0

---

docs/zh-cn/2.0.0/user_doc/architecture/design.md
site_config/docs2-0-0.js

up docs.2.0.0 

---

docs/zh-cn/2.0.0/user_doc/architecture/listdocs.md
site_config/docs2-0-0.js

add list docs

---

community/en-us/release-post.md
community/zh-cn/release-post.md

ref: https://github.com/apache/dolphinscheduler/pull/6793

Add change github issue template after release post

---

blog/zh-cn/DS-2.0-alpha-release.md

在经过团队和社区贡献者两年多的共同努力之下，我们宣布 Apache DolphinScheduler 2.0 将很快与大家见面。2.0 版本即将有多项大家期待已久的重大更新，在 DolphinScheduler 的发展中再立里程碑。但为了给用户带来更好的体验，社区决定 alpha 版本先行，将用户的反馈和建议融汇进正式版本之中。

DS 2.0 alpha release

---

docs/en-us/2.0.0/user_doc/architecture/listdocs.md

updata listdocs.md

---

blog/en-us/DS-2.0-alpha-release(En).md
blog/zh-cn/DS-2.0-alpha-release.md
site_config/blog.js

Hello community, good news! After nearly 10 months of joint efforts by more than 100 community contributors, we are happy to announce the release of Apache DolphinScheduler 2.0 alpha.

DS 2.0 alpha release(En)

---

community/en-us/release-prepare.md
community/zh-cn/release-prepare.md
docs/en-us/1.3.4/user_doc/docker-deployment.md
docs/en-us/1.3.5/user_doc/docker-deployment.md
docs/en-us/1.3.5/user_doc/kubernetes-deployment.md
docs/en-us/1.3.6/user_doc/docker-deployment.md
docs/en-us/1.3.6/user_doc/kubernetes-deployment.md
docs/en-us/1.3.8/user_doc/docker-deployment.md
docs/en-us/1.3.8/user_doc/kubernetes-deployment.md
docs/en-us/1.3.9/user_doc/docker-deployment.md
docs/en-us/1.3.9/user_doc/kubernetes-deployment.md
docs/en-us/2.0.0/user_doc/guide/installation/docker.md
docs/en-us/2.0.0/user_doc/guide/installation/kubernetes.md
docs/en-us/dev/user_doc/guide/installation/docker.md
docs/en-us/dev/user_doc/guide/installation/kubernetes.md
docs/zh-cn/1.3.4/user_doc/docker-deployment.md
docs/zh-cn/1.3.5/user_doc/docker-deployment.md
docs/zh-cn/1.3.5/user_doc/kubernetes-deployment.md
docs/zh-cn/1.3.6/user_doc/docker-deployment.md
docs/zh-cn/1.3.6/user_doc/kubernetes-deployment.md
docs/zh-cn/1.3.8/user_doc/docker-deployment.md
docs/zh-cn/1.3.8/user_doc/kubernetes-deployment.md
docs/zh-cn/1.3.9/user_doc/docker-deployment.md
docs/zh-cn/1.3.9/user_doc/kubernetes-deployment.md
docs/zh-cn/2.0.0/user_doc/guide/installation/docker.md
docs/zh-cn/2.0.0/user_doc/guide/installation/kubernetes.md
docs/zh-cn/dev/user_doc/guide/installation/docker.md
docs/zh-cn/dev/user_doc/guide/installation/kubernetes.md

ATT, PTAL @CalvinKirs @lenboo @kezhenxu94

Use docker.scarf.sh in docker pull to track docker user info

---

sitemap.xml

updata sitemap.xml

---

redirect.ejs
sitemap.xml
template.ejs

add Global site tag (gtag.js) - Google Analytics

add Global site tag (gtag.js) - Google Analytics

---

googled0df7b96f277a143.html
redirect.ejs
site_config/site.js
sitemap.xml
template.ejs

updata site.js

---

site_config/docs2-0-0.js

updata docs2.0.0

---

site_config/docs2-0-0.js

title: 'User Manual', TO   title: 'Introduction to Functions',
title: 'Architecture Design', TO    title: 'Advanced Guide',

updata docs.2.0.0 

---

site_config/docs2-0-0.js

update guide tree

---

docs/en-us/2.0.0/user_doc/guide/homepage.md

updata homepage.md

---

community/en-us/development/submit-code.md
community/zh-cn/development/submit-code.md

remove dead links

---

site_config/home.jsx

updata home

---

site_config/site.js

Fix hyperlink error

---

site_config/site.js

close [#7394](https://github.com/apache/dolphinscheduler/issues/7394)

[Feature] The official website adds `1.3.9` documents.

---

docs/en-us/2.0.0/user_doc/guide/installation/hardware.md
docs/en-us/dev/user_doc/guide/installation/hardware.md

fix mis-written word in 'hardware.md'
change some sub-titles first letters to capital

[Bug-6939][website] Miswritten word in 'hardware.md'

---

site_config/development.js

ref: https://github.com/apache/dolphinscheduler-website/pull/566 and https://github.com/apache/dolphinscheduler-website/pull/500

Remove plugin sidebar and add datasource

---

src/components/header/index.jsx

Delete the extra brace

---

.asf.yaml

strict merge way to avoid some commit like 79e1334a09fee22248dea413704ab2a04de33675 and ee6c4ae2f810201ee39a3f38e74f50992c9d6848

Add asf config to strict behavior

---

docs/en-us/dev/user_doc/guide/datasource/hive.md
docs/zh-cn/dev/user_doc/guide/datasource/hive.md

- update data source center doc in user guide

update data source center doc in user guide

---

.asf.yaml

In 8cefcc4 I delete the website config by accident, It cause our website would not be auto deploy. Tihis patch recover the asf config for website

Recover website deploy configuration

---

community/en-us/development/subscribe.md
community/zh-cn/development/subscribe.md

Add unsubscribe method to website both in docs and docs-zh.  Close apache/dolphinscheduler#7419

[Feature-7419][Website][docs][doc-zh]Add unsubscribe method to website

---

.github/workflows/dead-link-checker.yaml

This reverts commit f344ff32 , recover GA dead link checker

Revert "[Fix] Update youzan. (#586)"

---

site_config/community.jsx

add instructions to unsubscribe the mailing list

---

docs/en-us/dev/user_doc/architecture/design.md

https://github.com/apache/dolphinscheduler/issues/7496

solve the issues-7496 by replacing with en picture

---

blog/en-us/Apache-DolphinScheduler-2.0.1.md
site_config/blog.js
site_config/home.jsx

add  Apache DolphinScheduler 2.0.1

add  Apache DolphinScheduler 2.0.1

---

blog/en-us/Apache-DolphinScheduler-2.0.1.md
site_config/blog.js
site_config/home.jsx

updata img link

---

site_config/home.jsx

updata link

---

development/en-us/development-environment-setup.md
development/zh-cn/development-environment-setup.md

related issue 
> [apache/dolphinscheduler#7553](https://github.com/apache/dolphinscheduler/issues/7553)

[FAQ-7553][doc] : add the VM Options of the specified configuration

---

docs/en-us/1.3.9/user_doc/skywalking-agent-deployment.md
docs/en-us/2.0.0/user_doc/guide/observability/skywalking-agent.md
docs/en-us/2.0.1/user_doc/guide/observability/skywalking-agent.md
docs/zh-cn/1.3.9/user_doc/skywalking-agent-deployment.md
docs/zh-cn/2.0.0/user_doc/guide/observability/skywalking-agent.md
docs/zh-cn/2.0.1/user_doc/guide/observability/skywalking-agent.md
site_config/docs1-3-9.js
site_config/docs2-0-0.js
site_config/docs2-0-1.js

We just move version after 1.3.9 cause >1.3.9 is LTS

Move skywalking-agent to observability(1.3.9-2.0.2)

---

docs/en-us/2.0.0/user_doc/architecture/configuration.md
docs/en-us/2.0.1/user_doc/architecture/configuration.md
docs/en-us/2.0.2/user_doc/architecture/configuration.md
docs/zh-cn/2.0.0/user_doc/architecture/configuration.md
docs/zh-cn/2.0.1/user_doc/architecture/configuration.md
docs/zh-cn/2.0.2/user_doc/architecture/configuration.md

This pr will close apache/dolphinscheduler#7838

[Fix-7838]Modify ZK related docs after version 2.0

---

docs/en-us/2.0.2/user_doc/guide/alert/enterprise-wechat.md
docs/en-us/dev/user_doc/guide/alert/enterprise-wechat.md
docs/zh-cn/2.0.2/user_doc/guide/alert/enterprise-wechat.md
docs/zh-cn/dev/user_doc/guide/alert/enterprise-wechat.md

Optimize alert document format

Optimize alert doc format

---

blog/en-us/Apache-DolphinScheduler-2.0.1.md
blog/en-us/Awarded_most_popular_project_in_2021.md
blog/en-us/DS-2.0-alpha-release.md
blog/en-us/Eavy_Info.md
blog/en-us/Introducing-Apache-DolphinScheduler-1.3.9.md
blog/en-us/Lizhi-case-study.md
blog/en-us/Twos.md
blog/en-us/YouZan-case-study.md
blog/zh-cn/Apache-DolphinScheduler-2.0.1.md
blog/zh-cn/Awarded_most_popular_project_in_2021.md
blog/zh-cn/DS-2.0-alpha-release.md
blog/zh-cn/Eavy_Info.md
blog/zh-cn/Lizhi-case-study.md
blog/zh-cn/Twos.md
blog/zh-cn/YouZan-case-study.md
site_config/home.jsx

updata  link

---

community/en-us/join/review.md
community/en-us/team.md
community/zh-cn/join/review.md
community/zh-cn/team.md
site_config/community.jsx

Add a guide about how to reviw issue and PR for DolphinScheduler

[community] Add how to review issue or PR

---

docs/en-us/2.0.0/user_doc/guide/installation/pseudo-cluster.md
docs/en-us/2.0.1/user_doc/guide/installation/pseudo-cluster.md
docs/en-us/2.0.2/user_doc/guide/installation/pseudo-cluster.md
docs/en-us/2.0.3/user_doc/guide/installation/pseudo-cluster.md
docs/en-us/dev/user_doc/guide/installation/pseudo-cluster.md
docs/zh-cn/2.0.0/user_doc/guide/installation/pseudo-cluster.md
docs/zh-cn/2.0.1/user_doc/guide/installation/pseudo-cluster.md
docs/zh-cn/2.0.2/user_doc/guide/installation/pseudo-cluster.md
docs/zh-cn/2.0.3/user_doc/guide/installation/pseudo-cluster.md
docs/zh-cn/dev/user_doc/guide/installation/pseudo-cluster.md

This closes [apache/dolphinscheduler issues 7844](https://github.com/apache/dolphinscheduler/issues/7844)

[Fix-7844][docs] fix nnfriendliness and errors in the 2.x deployment documents

---

community/en-us/development/unit-test.md
community/zh-cn/development/unit-test.md
site_config/community.jsx

When I read the documentation for [unit test](https://dolphinscheduler.apache.org/zh-cn/community/development/unit-test.html), I found that there was no relevant English documentation, so I translated it.

Unit test English version

---

.github/workflows/website.yml
site_config/site.js

Add new python dist doc to website

[feat] Add python dist doc to document

---

.github/workflows/website.yml

ref: apache/dolphinscheduler#8210. we change the requested and we should also change in website, cause python doc build based on it

[fix] CI ds python build

---

docs/en-us/2.0.3/user_doc/About_DolphinScheduler/About_DolphinScheduler.md
docs/en-us/dev/user_doc/About_DolphinScheduler/About_DolphinScheduler.md
docs/zh-cn/2.0.3/user_doc/About_DolphinScheduler/About_DolphinScheduler.md
docs/zh-cn/dev/user_doc/About_DolphinScheduler/About_DolphinScheduler.md

Signed-off-by: kodalien <kkodalien@gmail.com>

[Docs] Change about dolphinscheduler About_DolphinScheduler.md

---

docs/en-us/release/faq.md
docs/zh-cn/release/faq.md

related pr: https://github.com/apache/dolphinscheduler/issues/427

[Docs] Add multi-cluster support faq

---

community/en-us/release-prepare.md
community/en-us/release.md
community/zh-cn/release-prepare.md
community/zh-cn/release.md

Related to apache/dolphinscheduler#8343
we have to add python distribute the package to ASF dist, So we must change some release process

[community] Add content about release python api

---

docs/en-us/dev/user_doc/guide/task/emr.md
docs/zh-cn/dev/user_doc/guide/task/emr.md
site_config/docsdev.js

doc for this pr https://github.com/apache/dolphinscheduler/pull/8503

[doc] Add task plugin doc of EMR

---

site_config/docsdev.js

This patch correct the missing link for alert plugin:
* telegram
* dingtalk
* webexteams

Add missing sidebar for alert plugin in dev doc

---

community/en-us/release-post.md
community/zh-cn/release-post.md

Add two missing steps in release-post , including:
* change history-versions.md
* release Python API to PyPI

Add new steps in release-post include history-version and pypi release

---

community/en-us/release.md
community/zh-cn/release.md

We do no need to change release.md when we trying to release.
It will change to release-post.md

[community] Remove change download page in release.md

---

docs/en-us/dev/user_doc/guide/datasource/hive.md
docs/en-us/dev/user_doc/guide/datasource/introduction.md
docs/en-us/dev/user_doc/guide/datasource/mysql.md
docs/en-us/dev/user_doc/guide/datasource/postgresql.md
docs/en-us/dev/user_doc/guide/datasource/spark.md
docs/zh-cn/dev/user_doc/guide/datasource/mysql.md
docs/zh-cn/dev/user_doc/guide/datasource/postgresql.md

fix
proofreading dev documents under /user_doc/guide/datasource

fix-dev documents under /user_doc/guide/datasource

---

docs/en-us/dev/user_doc/guide/alert/alert_plugin_user_guide.md
docs/en-us/dev/user_doc/guide/alert/dingtalk.md
docs/en-us/dev/user_doc/guide/alert/enterprise-webexteams.md
docs/en-us/dev/user_doc/guide/alert/enterprise-wechat.md
docs/en-us/dev/user_doc/guide/alert/telegram.md
docs/zh-cn/dev/user_doc/guide/alert/telegram.md

fix
proofreading dev documents under /user_doc/guide/alert

fix-dev documents under /user_doc/guide/alert

---

docs/en-us/dev/user_doc/guide/installation/cluster.md
docs/en-us/dev/user_doc/guide/installation/docker.md
docs/en-us/dev/user_doc/guide/installation/hardware.md
docs/en-us/dev/user_doc/guide/installation/kubernetes.md
docs/en-us/dev/user_doc/guide/installation/pseudo-cluster.md
docs/en-us/dev/user_doc/guide/installation/skywalking-agent.md
docs/en-us/dev/user_doc/guide/installation/standalone.md

Proofreading dev documents under /user_doc/guide/installation

Proofreading dev documents under /user_doc/guide/installation

---

site_config/home.jsx

change the official website introduction content

change the official website introduction

---

docs/en-us/dev/user_doc/architecture/configuration.md
docs/en-us/dev/user_doc/architecture/design.md
docs/en-us/dev/user_doc/architecture/task-structure.md
docs/en-us/dev/user_doc/guide/alert/dingtalk.md
docs/en-us/dev/user_doc/guide/alert/enterprise-webexteams.md
docs/en-us/dev/user_doc/guide/alert/enterprise-wechat.md
docs/en-us/dev/user_doc/guide/alert/telegram.md
docs/en-us/dev/user_doc/guide/installation/docker.md
docs/en-us/dev/user_doc/guide/installation/hardware.md
docs/en-us/dev/user_doc/guide/installation/kubernetes.md
docs/en-us/dev/user_doc/guide/installation/pseudo-cluster.md
docs/en-us/dev/user_doc/guide/installation/standalone.md
docs/en-us/dev/user_doc/guide/parameter/context.md
docs/en-us/dev/user_doc/guide/parameter/priority.md
docs/en-us/dev/user_doc/guide/project/workflow-definition.md
docs/en-us/dev/user_doc/guide/task/datax.md
docs/en-us/dev/user_doc/guide/task/flink.md
docs/en-us/dev/user_doc/guide/task/map-reduce.md
docs/en-us/dev/user_doc/guide/task/spark.md
docs/en-us/dev/user_doc/guide/task/sql.md
docs/en-us/dev/user_doc/guide/task/switch.md

fix all the 'as follow' grammar

fix all the 'as follow' grammar

---

development/en-us/e2e-test.md
development/zh-cn/e2e-test.md
docs/en-us/2.0.5/user_doc/guide/upgrade.md
docs/zh-cn/2.0.5/user_doc/guide/upgrade.md

Related pr & issue:
https://github.com/apache/dolphinscheduler/pull/9077
https://github.com/apache/dolphinscheduler/issues/9068

[Feature][e2e] Suggest e2e test adapt M1 chip

---

docs/en-us/dev/user_doc/guide/alert/telegram.md
docs/zh-cn/dev/user_doc/guide/alert/telegram.md

declare JSON body feature to the telegram.md

[Fix] [Website-9173]declare JSON body feature to the telegram.md

---

community/en-us/team.md
community/zh-cn/team.md
development/en-us/e2e-test.md
development/zh-cn/e2e-test.md

add committer and fix e2e doc broken url

[Doc] add committer and fix e2e doc broken url

---

src/components/header/index.jsx
src/components/header/index.scss

[Feature]Added banner Prompt

---

.asf.yaml

Avoiding committer force push and overwrite some
content

[ci] Add branch history-docs as protect branch

---

development/en-us/development-environment-setup.md
development/zh-cn/development-environment-setup.md

update compile command

---

site_config/home.jsx

close: apache/dolphinscheduler#9738

[Bug]fix Chinese Official website link error link

---

site_config/development.js

https://github.com/apache/dolphinscheduler/pull/10442

[dev] Add api test doc sidebar

---

site_config/home.jsx

users yili only show in English version of document but not in Chinese one, this patch make it work in Chinese too
ref #803

fix: users yili not show bug

---

.dlc.json
docs/1.3.5/docs/en/kubernetes-deployment.md
docs/1.3.5/docs/zh/kubernetes-deployment.md
docs/1.3.6/docs/en/kubernetes-deployment.md
docs/1.3.6/docs/zh/kubernetes-deployment.md
docs/1.3.8/docs/en/kubernetes-deployment.md
docs/1.3.8/docs/zh/kubernetes-deployment.md
docs/1.3.9/docs/en/kubernetes-deployment.md
docs/1.3.9/docs/zh/kubernetes-deployment.md
docs/2.0.0/docs/en/guide/installation/kubernetes.md
docs/2.0.0/docs/zh/guide/installation/kubernetes.md
docs/2.0.1/docs/en/guide/installation/kubernetes.md
docs/2.0.1/docs/zh/guide/installation/kubernetes.md
docs/2.0.2/docs/en/guide/installation/kubernetes.md
docs/2.0.2/docs/zh/guide/installation/kubernetes.md
docs/2.0.3/docs/en/guide/installation/kubernetes.md
docs/2.0.3/docs/zh/guide/installation/kubernetes.md
docs/2.0.5/docs/en/guide/installation/kubernetes.md
docs/2.0.5/docs/zh/guide/installation/kubernetes.md

ref: apache/dolphinscheduler#10567

fix: k8s bitnami repo index error

---

community/en-us/development/document.md
community/zh-cn/development/document.md

the update adds the documentation instructions for starting the documentation

the update adds the documentation instructions for starting the documentation

---

community/en-us/team.md
community/zh-cn/team.md

[Chore] Add pmc members

---

community/en-us/team.md

[Chore] Fix format

---

blog/en-us/Apache_dolphinScheduler_3.0.1.md
site_config/blog.js
site_config/home.jsx

Apache DolphinScheduler 3.0.1 released, with the scheduling kernel and UI optimized

add nesw Blog 

---

scripts/conf.sh

Add new release for version 207

new release version 207

---

.github/workflows/dead-link-checker.yaml

Do not check all the docs when submit new PR, should only check in schedule event

[feat] Only check all docs dead link in schedule event

---

.github/workflows/dead-link-checker.yaml

Will check all history docs when event is schedule, will cost many times in this case, so we need more time

[ci] Add timeout threshold to schedule dead link check

---

.asf.yaml

[chore] Remove docs-checks for require context

---

public/worker/db.js
src/api/getDownload.js
src/api/getLocales.js
src/views/Documentation/SearchModal.jsx
src/views/Documentation/index.jsx
src/views/Documentation/useSearch.js

* documentation search error
* add cached data

[Fix] Revise bugs.

---

scripts/generate_docs.js
scripts/parse_md.js
scripts/replace_links.js
src/components/Connect/index.scss
src/views/Documentation/detail.scss

ref [#13189](https://github.com/apache/dolphinscheduler/issues/13189)

[Fix] Fix links and connect UI.

---

public/index.html
sitemap.xml
src/components/NavBar/index.scss
src/styles/mixin.scss
src/views/Download/deployment.scss
src/views/Download/index.scss
src/views/Download/version.scss
src/views/Home/index.scss

* Added `sitemap.xml`
* Revise some uis
* Added baidu hm

[Fix] Some changes.

---

blog/en-us/DolphinScheduler_launches_aws_ami.md
blog/en-us/DolphinScheduler_python_api_ci_cd.md
config/blog/en-us/release.json
config/blog/en-us/tech.json

config in json should equal to file name

fix: deadlink for our blog

---

config/download.json
scripts/conf.sh

[Release] Release version 3.1.3

---

scripts/replace_links.js

temp fix: https://github.com/apache/dolphinscheduler/issues/13362

fix: Regexp replace all datasource-setting hyper link

---

config/download.json
scripts/conf.sh

add 3.1.4 release

---

.github/workflows/website.yml
config/blog/en-us/release.json
config/blog/en-us/user.json

and error json config and add ci avoid
regression

fix: Deploy error and avoid regression

---

.asf.yaml

https://github.com/apache/dolphinscheduler-website/pull/906
https://github.com/apache/dolphinscheduler-website/pull/905
https://github.com/apache/dolphinscheduler-website/pull/904

disable dev bot update

---

.github/workflows/website.yml

Reverts apache/dolphinscheduler-website#928

Revert "update website yml"

---

blog/zh-cn/Apache_DolphinScheduler_releases_version_3.2.0.md
blog/zh-cn/Application_and_practice_of_Apache_DolphinScheduler_offline_scheduling_in_Ziroom_(real_estate_agency)_multi-business_scenario.md
blog/zh-cn/Big_Data_Scheduling_Best_Practices_Migrating_from_Airflow_to_Apache_DolphinScheduler.md
blog/zh-cn/How_can_real_estate_companies_let_data_analysts_do_the_work_of_professional_data_warehouse_engineers.md
blog/zh-cn/How_does_Apache_Dolphinscheduler_solve_the_infinite_loop_of_Master_service_without_restarting.md
blog/zh-cn/How_does_the_national_dairy_giant_Yili_open_up_a_path_for_enterprise_digital_transformation_based_on_Apache_DolphinScheduler.md
blog/zh-cn/The_implementation_practice_of_Apache_DolphinScheduler_as_a_unified_scheduling_center_in_Lenovo.md
blog/zh-cn/The_operation_practice_of_smooth_transition_from_Azkaban_to_Apache_DolphinScheduler.md
blog/zh-cn/Zhendao_Group_builds_an_intelligent_marketing_cloud_platform_based_on_Apache_DolphinScheduler.md

Our metadata section is an error
we should use this style for metadata
```md
---
title: Article title
keywords: Article keyword
description: Article description
---
```
```md
```yaml
title: Article title
keywords: Article keyword
description: Article description
```\ 
```

fix: Blog metadata error

---

config/download.json
scripts/conf.sh

[3.1.9] add 3.1.9 release

---

public/index.html

related to https://whimsy.apache.org/site/project/dolphinscheduler, https://github.com/apache/dolphinscheduler/issues/15505

fix: Remove external resources

---

config/download.json
scripts/conf.sh

new release verison in Chinese New year.

release: version 3.2.1

---

README.md

Optimize doc

---

public/index.html

ref: https://github.com/apache/dolphinscheduler/issues/15505

fix apache link bug

---

public/index.html

ref: https://github.com/apache/dolphinscheduler/issues/15505

add copyright of index

---

blog/en-us/Deploy_the_serverless_Apache_DolphinScheduler_task_scheduling_system_on_AWS.md
src/views/Download/Deployment.jsx
src/views/Download/Version.jsx

[Improvement] specify a stable version

---

public/.htaccess

try to fix #959 again.
ref: https://github.com/apache/apisix-website/pull/1774

chore: try to fix integrate kapa into website

---

public/.htaccess
src/components/Footer/index.jsx

Temporarily removed kapa.ai because of apache's website policy.
ref: https://privacy.apache.org/policies/website-policy.html

chore: temporarily remove kapa

---

public/worker/db.js
scripts/generate_docs.js
src/views/Documentation/SearchModal.jsx
src/views/Documentation/helpers.js

1.fix search-result item url
fix https://github.com/apache/dolphinscheduler/issues/14108
- The current item link:
Unable to jump to the target page
- The Fix item link:
2. fix the english doc can not search
fix https://github.com/apache/dolphinscheduler/issues/14108
- Now English website can not search
- The fix search

[Fix] fix website search

---

public/index.html
public/manifest.json
src/components/NavBar/index.jsx
src/hooks/useVersions.js
src/views/Documentation/index.jsx

- Remove download button from index
- Disable download button in `dev`

[Bug] Fix download error

---

.dlc.json
.github/workflows/dead-link-checker.yaml
blog/zh-cn/Board_of_Directors_Report.md

Because no one would like to correct the DL, and workflow failed notification email full of me email

Disable deadlink check for related docs

---

config/download.json
scripts/conf.sh

pending merged until this pr is merged https://github.com/apache/dolphinscheduler/pull/17117

[Chore] Release 3.3.0-alpha

---

.asf.yaml

Base on jira: https://issues.apache.org/jira/projects/INFRA/issues/INFRA-26737

Dummy commit

---

README.md

Synchronizing changes to https://github.com/apache/dolphinscheduler/pull/17160 Copilot's found errors

[Doc] Modified README based on Copilot's comments

---

scripts/replace_links.js

Participate in contributing and Parameter Priority section inline link error, return [no data] status.

fix  part section inline link error
